## roles/ansible-role-powerline/tasks/main.yml
# vim:ft=yaml.ansible:
---
- include_tasks: '{{ pl_distro }}'
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"
  loop_control:
    loop_var: pl_distro
...
