## roles/ansible-role-powerline/tasks/main.yml
# vim:ft=ansible:
---
- include_tasks: '{{ item }}'
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"
...
